### ISSUE TITLE
Add recommended build instructions to the README

### ISSUE THREAD

**Issue by nickhammond** [telemetryapp/gotelemetry_agent#1]
Is it possible to add build instructions to the README? I'm not entirely familiar with Go but I'd like to use the agent in master so I can utilize the `verbose` flag that's been added. How are you guys currently building the agent for multiple platforms? I see the Makefile but make is failing when it tries to import in agent.go.

**Comment by mtabini** [comment]
Hi Nick—

We're in the process of pushing out an update in the next day or so—when we do that, I will make sure we add a full set of installation instructions to the docs.

**Comment by nickhammond** [comment]
@mtabini sounds good, thanks!

**Comment by mtabini** [comment]
Hi Nick—

The [new release](https://github.com/telemetryapp/gotelemetry_agent/releases/tag/1.2.0-RC1) is out. You will find many changes and improvements, which are fully documented on the [Telemetry documentation site](http://telemetry.readme.io/v1.0/docs/agents).

If you still want to build from source, it should be as easy as explained [in the docs](http://telemetry.readme.io/v1.0/docs/agent-setup). I'm going to close this issue for now—feel free to reopen if you're still having problems.

Thanks!

**Comment by nickhammond** [comment]
@mtabini Thanks for the update, really liking the changes in this release too.
