### ISSUE TITLE
Linux x64 agent for v2.0.0 Beta

### ISSUE THREAD

**Issue by rgelobterFH** [telemetryapp/gotelemetry_agent#8]
When I try to install the telemetry_agent-2.0.0_beta-1.x86_64.rpm I get an error "package telemetry_agent-2.0.0_beta-1.x86_64 is intended for a darwin operating system.". 

Are you sure this was compiled correctly? I think someone compiled MAC OSX inside the linux rpm. If I download the telemetry_agent_2.0.0_alpha-linux-amd64.zip it runs fine.

I am on CentOS 6.5  2.6.32 x86_64

**Comment by mtabini** [comment]
Thanks for the report—it looks like it was perhaps a problem on our end. Can you try again? I updated the binary in the release.

**Comment by rgelobterFH** [comment]
Looks good now, thanks!
